apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-service
  template:
    metadata:
      labels:
        app: comments-service
    spec:
      containers:
        - name: comments-service
          image: comments-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001