apiVersion: v1
kind: Service
metadata:
  name: blog-app-client-service
spec:
  type: LoadBalancer
  selector:
    app: blog-app-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
